# Generated by Django 2.1.3 on 2018-11-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20181106_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
            preserve_default=False,
        ),
    ]
