# Generated by Django 2.1.3 on 2018-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20181106_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stackcard',
            options={},
        ),
        migrations.AddField(
            model_name='stack',
            name='cards',
            field=models.ManyToManyField(through='cards.StackCard', to='cards.Card'),
        ),
        migrations.AlterUniqueTogether(
            name='stackcard',
            unique_together={('stack', 'card')},
        ),
    ]
